const HOME_SERVICE_IMAGES = [
  '/images/optimized/service-training-card-720.jpg',
  '/images/optimized/service-massage-card-720.jpg',
  '/images/optimized/service-getfit-card-720.jpg',
];

const PAGE_IMAGES = {
  hero: '/images/optimized/hero-desktop-1344.jpg',
  personalTraining: '/images/optimized/page-training-hero-960.jpg',
  massage: '/images/optimized/page-massage-hero-960.jpg',
  getFit: '/images/optimized/page-getfit-hero-960.jpg',
  about: '/images/optimized/page-about-hero-960.jpg',
  trainerDenBosch: '/images/optimized/service-training-card-960.jpg',
  massageDenBosch: '/images/optimized/service-massage-card-960.jpg',
};

export const DEFAULT_SITE_CONTENT = Object.freeze({
  hero_eyebrow: 'PERSONAL TRAINING • MASSAGE • VOEDINGSBEGELEIDING',
  hero_title: 'Word fitter, sterker en pijnvrij',
  hero_highlight: 'met een complete aanpak',
  hero_subtitle:
    'Bij JitanSports combineren we personal training, deep tissue massage en voedingsbegeleiding voor blijvend resultaat. Persoonlijke aandacht. Gericht op jouw doelen. Voor lichaam én geest.',
  hero_image: PAGE_IMAGES.hero,
  primary_cta_text: 'Plan gratis proefles',
  secondary_cta_text: 'WhatsApp direct',
  cta_title: 'Klaar om fitter, sterker en energieker te worden?',
  cta_subtitle:
    'Plan vandaag nog jouw gratis proefles en ontdek welke aanpak bij jouw lichaam, agenda en doel past.',
  phone_display: '06 82 27 26 80',
  phone_href: '+31682272680',
  whatsapp_number: '31682272680',
  whatsapp_message: 'Hallo JitanSports, ik wil graag een gratis proefles aanvragen.',
  email: 'info@jitan-sports.nl',
  region: 'omgeving Den Bosch',
  address_label: 'Omgeving Den Bosch',
  instagram_url: 'https://instagram.com',
  facebook_url: 'https://facebook.com',
  linkedin_url: 'https://linkedin.com',
  seo_title: 'JitanSports - Personal Trainer & Massage omgeving Den Bosch',
  seo_description:
    'Personal training, deep tissue massage en voedingsbegeleiding in omgeving Den Bosch. Plan gratis een proefles bij JitanSports.',
  seo_image: PAGE_IMAGES.hero,
  seo_home_title: 'Personal Trainer Den Bosch, Massage & Voeding | JitanSports',
  seo_home_description: 'Personal training, Deep Tissue Massage en voedingsbegeleiding in Den Bosch, Rosmalen, Vught en omgeving. Plan gratis een proefles.',
  seo_personal_training_title: 'Personal Training omgeving Den Bosch - Outdoor & Aan Huis | JitanSports',
  seo_personal_training_description:
    '1-op-1 personal training in omgeving Den Bosch. Outdoor, aan huis, duo-training en voedingsadvies. Start met een gratis proefles.',
  seo_massage_title: 'Deep Tissue Massage omgeving Den Bosch - Aan Huis | JitanSports',
  seo_massage_description:
    'Professionele deep tissue massage en ontspanningsmassage in omgeving Den Bosch. Gericht op herstel, pijnvermindering en ontspanning.',
  seo_get_fit_title: 'Get Fit Pakket omgeving Den Bosch - 12 Weken Coaching | JitanSports',
  seo_get_fit_description:
    'Een compleet 12-weken traject met personal training, voeding, lichaamsanalyse, massage en coaching.',
  seo_about_title: 'Over JitanSports - Personal Trainer omgeving Den Bosch',
  seo_about_description:
    'Leer JitanSports kennen: personal training, massage en voedingsbegeleiding met een persoonlijke aanpak in omgeving Den Bosch.',
  seo_pricing_title: 'Tarieven Personal Training & Massage | JitanSports',
  seo_pricing_description:
    'Bekijk de tarieven voor personal training, deep tissue massage, ontspanningsmassage en het Get Fit pakket.',
  seo_blog_title: 'Blog over Training, Massage en Gezondheid | JitanSports',
  seo_blog_description:
    'Tips en inzichten over personal training, massage, voeding, herstel en een gezonde lifestyle.',
  seo_faq_title: 'Veelgestelde Vragen | JitanSports',
  seo_faq_description:
    'Antwoorden op veelgestelde vragen over personal training, massage, tarieven, proeflessen en afspraken bij JitanSports.',
  seo_contact_title: 'Contact met JitanSports | Personal Trainer omgeving Den Bosch',
  seo_contact_description:
    'Neem contact op met JitanSports voor personal training, massage, voedingsadvies of een gratis proefles in omgeving Den Bosch.',
  seo_booking_title: 'Afspraak Plannen | JitanSports',
  seo_booking_description:
    'Plan direct een gratis proefles, personal training sessie of massage bij JitanSports.',
  seo_trainer_den_bosch_title: 'Personal Trainer omgeving Den Bosch | JitanSports',
  seo_trainer_den_bosch_description:
    'Personal trainer in omgeving Den Bosch voor afvallen, krachttraining, conditie en voedingsbegeleiding. Gratis proefles.',
  seo_massage_den_bosch_title: 'Massage omgeving Den Bosch - Deep Tissue & Ontspanning | JitanSports',
  seo_massage_den_bosch_description:
    'Massage in omgeving Den Bosch aan huis of op locatie. Deep tissue massage en ontspanningsmassage voor herstel en ontspanning.',
  seo_deep_tissue_den_bosch_title: 'Deep Tissue Massage omgeving Den Bosch | JitanSports',
  seo_deep_tissue_den_bosch_description:
    'Deep tissue massage in omgeving Den Bosch voor rugklachten, nek- en schouderpijn, spierherstel en sportblessures.',

  home_review_proof: '100+ tevreden klanten gingen je voor',
  home_services_eyebrow: 'Wat wij bieden',
  home_services_title: 'Onze diensten',
  home_service_1_title: 'Personal Training',
  home_service_1_desc: '1-op-1 begeleiding outdoor of aan huis. Op jouw tempo, naar jouw doel.',
  home_service_1_image: HOME_SERVICE_IMAGES[0],
  home_service_1_link: '/personal-training',
  home_service_1_cta: 'Meer info',
  home_service_2_title: 'Deep Tissue Massage',
  home_service_2_desc: 'Professionele massage voor herstel, ontspanning en pijnvermindering.',
  home_service_2_image: HOME_SERVICE_IMAGES[1],
  home_service_2_link: '/massage',
  home_service_2_cta: 'Meer info',
  home_service_3_title: 'Get Fit Programma',
  home_service_3_desc: '12 weken intensief traject inclusief voeding en persoonlijke coaching.',
  home_service_3_image: HOME_SERVICE_IMAGES[2],
  home_service_3_link: '/get-fit',
  home_service_3_cta: 'Meer info',
  home_mid_cta_title: 'Klaar om te starten?',
  home_mid_cta_text: 'Plan vandaag nog je gratis proefles en ontdek wat JitanSports voor jou kan betekenen.',
  home_mid_cta_button: 'Start Vandaag',
  home_about_eyebrow: 'Over JitanSports',
  home_about_title: 'Ontmoet Jitan - jouw persoonlijke coach',
  home_about_text:
    'JitanSports is ontstaan vanuit ervaring. Ook na je veertigste kun je nog steeds fit, energiek en zelfverzekerd zijn. Met jarenlange ervaring in personal training, voeding en massage helpt Jitan klanten stap voor stap naar een gezondere lifestyle.',
  home_about_image: PAGE_IMAGES.hero,
  home_about_usps:
    'Jarenlange ervaring\nVintage Krachttraining\nDeep Tissue Massage specialist\nVoedingsbegeleiding\nLuisterend oor\nStap voor stap begeleiding',
  home_about_button: 'Meer over Jitan',
  home_faq_title: 'Veelgestelde vragen',
  home_faq_1_question: 'Waar trainen we?',
  home_faq_1_answer: 'JitanSports traint aan huis, in het park of op een locatie die jou uitkomt in omgeving Den Bosch.',
  home_faq_2_question: 'Hoe lang duurt een sessie?',
  home_faq_2_answer: 'Een standaard trainingssessie duurt 60 minuten. Massages zijn 60 of 90 minuten.',
  home_faq_3_question: 'Is de gratis proefles echt gratis?',
  home_faq_3_answer: 'Ja, 100% gratis en volledig vrijblijvend. Je ontdekt hoe wij werken en of het bij je past.',
  home_faq_4_question: 'Kan ik training en massage combineren?',
  home_faq_4_answer: 'Absoluut. Veel klanten combineren personal training met Deep Tissue Massage voor het beste resultaat.',

  goal_eyebrow: 'Jouw doel, ons resultaat',
  goal_title: 'Wat wil jij bereiken?',
  goal_1_title: 'Afvallen',
  goal_1_text: 'Bereik een gezond gewicht zonder crashdieten. Duurzaam, veilig en met blijvend resultaat.',
  goal_1_cta: 'Start nu',
  goal_1_link: '/get-fit',
  goal_2_title: 'Meer Energie',
  goal_2_text: 'Voel je fitter en energieker gedurende de dag. Stop met uitgeput wakker worden.',
  goal_2_cta: 'Ontdek meer',
  goal_2_link: '/personal-training',
  goal_3_title: 'Minder Pijnklachten',
  goal_3_text: 'Verminder rug-, nek- en schouderklachten door de kracht van massage en gerichte training.',
  goal_3_cta: 'Meer info',
  goal_3_link: '/massage',
  goal_4_title: 'Sterker en Fitter',
  goal_4_text: 'Verbeter kracht, conditie en zelfvertrouwen. Ontdek wat jouw lichaam echt kan.',
  goal_4_cta: 'Plan proefles',
  goal_4_link: '/booking',
  stat_1_value: '10+',
  stat_1_label: 'Jaar ervaring',
  stat_2_value: '100+',
  stat_2_label: 'Tevreden klanten',
  stat_3_value: '500+',
  stat_3_label: 'Trainingen gegeven',
  stat_4_value: 'Gratis',
  stat_4_label: 'Proefles voor iedereen',
  gallery_eyebrow: 'Galerij',
  gallery_title: 'Trainingen in de praktijk',

  pt_hero_image: PAGE_IMAGES.personalTraining,
  pt_hero_eyebrow: 'Personal Training',
  pt_hero_title: 'Personal Training op zijn best',
  pt_hero_subtitle: 'Daar waar jij je prettig voelt, daar trainen wij.',
  pt_banner_text: 'Ervaar het zelf met een gratis proefles!',
  pt_banner_button: 'Plan Gratis Proefles',
  pt_main_title: 'Training op jouw manier',
  pt_main_text:
    'Wij zijn ervan overtuigd dat jij het beste uit jezelf kunt halen op een plek waar jij jezelf goed voelt. Voor de een is dit buiten en voor de ander thuis. Daarom geven wij onze Personal Training buiten in de natuur of bij jou thuis.\nNeem voor, na of tijdens een drukke werkdag een moment voor jezelf en train in de buitenlucht. De natuur werkt ontspannend en rustgevend waardoor jij jezelf kunt opladen met een training op maat.\nMet slechts een training per week kunnen we al hele mooie resultaten behalen. Wij zorgen voor een gestructureerde aanpak, een training op maat om jouw fitnessdoelen te behalen.',
  pt_benefits:
    'Training op maat, afgestemd op jouw doelen\nOutdoor in de natuur of bij jou thuis\nAlle sportmaterialen worden meegenomen\nAl resultaat met 1x per week trainen\nDuo-training mogelijk (+€10 per persoon)\nGratis en vrijblijvende proefles',
  pt_feature_1_title: 'DUO Training',
  pt_feature_1_text: "Alleen trainen is top! Maar het kan ook met z'n tweeen of meer. Train samen met je partner, vriend(in) of familielid voor extra motivatie.",
  pt_feature_2_title: 'In een uur bereik je veel',
  pt_feature_2_text: 'Met ons gerichte trainingsprogramma, op basis van krachttraining, activeren wij doelgericht spiergroepen die jou helpen sterker te worden.',
  pt_feature_3_title: 'Outdoor en Aan Huis',
  pt_feature_3_text: 'Jij kiest waar je traint. Buiten in het park of in je eigen woonkamer. Wij zorgen voor alle benodigde sportmaterialen.',
  pt_feature_4_title: 'Zwangerschapstraining',
  pt_feature_4_text: 'Trainen voor, tijdens en na je zwangerschap? Ja dat kan! We trainen met een aangepast trainingsschema, veilig en verantwoord.',
  pt_nutrition_title: 'Voeding en Training gaan hand in hand',
  pt_nutrition_text:
    'Naast trainen kan voeding heel veel betekenen voor het behalen van jouw doelen. Of je nu wilt afvallen, aankomen, spieropbouw nastreeft of je gezondheid wilt verbeteren.\nSamen bespreken we jouw doelen en maken we een voedingsplan dat volledig is afgestemd op jouw persoonlijke situatie. Geen crashdieten, maar een haalbaar plan dat bij jou past.',
  pt_nutrition_button: 'Vraag Voedingsadvies Aan',
  pt_faq_title: 'Veelgestelde Vragen',
  pt_faq_1_question: 'Hoe lang duurt een training?',
  pt_faq_1_answer: 'Een trainingssessie duurt een uur. In dat uur kunnen we met een gestructureerde aanpak heel veel bereiken.',
  pt_faq_2_question: 'Kan ik ook zwanger trainen?',
  pt_faq_2_answer: 'Ja, we bieden zwangerschapstraining aan. We passen het schema veilig en verantwoord aan op jouw trimester en niveau.',
  pt_faq_3_question: 'Wat als het regent bij outdoor training?',
  pt_faq_3_answer: 'We trainen in principe buiten, ook bij lichte regen. Bij extreem weer wijken we uit naar een alternatieve locatie of training aan huis.',
  pt_faq_4_question: 'Moet ik al fit zijn om te beginnen?',
  pt_faq_4_answer: 'Nee. We passen alles aan op jouw niveau. Of je nu beginner bent of al ervaring hebt, we starten waar jij bent.',

  massage_hero_image: PAGE_IMAGES.massage,
  massage_hero_eyebrow: 'Massage',
  massage_hero_title: 'Deep Tissue & Ontspanningsmassage',
  massage_hero_subtitle: 'Herstel, ontspan en voel je weer helemaal goed.',
  massage_banner_text: 'Boek vandaag nog jouw massage!',
  massage_banner_button: 'Maak Afspraak',
  massage_popular_label: 'Meest Populair',
  massage_main_title: 'Deep Tissue Massage',
  massage_main_text:
    'Deep Tissue Massage is een krachtige massage met een ontzettend positief effect op het lichaam. Bij deze vorm van massage wordt vastzittend bindweefsel los gemasseerd waardoor blokkades worden verholpen.\nDe focus ligt op het verhelpen van lichaamsklachten zoals chronische nek-, schouder- en lage rugpijn, verkrampte spieren en beknelde zenuwen.',
  massage_benefits:
    'Verhelpt chronische nek-, schouder- en rugpijn\nMaakt vastzittend bindweefsel los\nVermindert verkrampte spieren\nHelpt bij beknelde zenuwen\nVerbetert sportprestaties en herstel\nDiepgaande en langdurige verlichting',
  massage_price_text: '€75,00',
  massage_price_subtext: '/ uur (full body)',
  massage_card_1_title: 'Ontspanningsmassage',
  massage_card_1_text: 'Heeft als doel jou lichamelijk en geestelijk tot rust te brengen. Geeft je een prettig en ontspannen gevoel.',
  massage_card_1_price: '€60,00 / uur',
  massage_card_2_title: 'Massage Aan Huis',
  massage_card_2_text: 'Wij komen met onze professionele massagetafel bij jou thuis. Geen reistijd en je kunt meteen in je eigen omgeving ontspannen.',
  massage_card_2_price: 'Geen extra kosten',
  massage_process_title: 'Het Herstelproces',
  massage_step_1_title: 'Intake',
  massage_step_1_text: 'We bespreken jouw klachten en wensen',
  massage_step_2_title: 'Behandeling',
  massage_step_2_text: 'Gerichte massage op probleemgebieden',
  massage_step_3_title: 'Herstel',
  massage_step_3_text: 'Ontspan in je eigen omgeving na de sessie',
  massage_cta_title: 'Tijd voor ontspanning?',
  massage_cta_subtitle: 'Boek vandaag nog jouw Deep Tissue of Ontspanningsmassage.',

  getfit_hero_image: PAGE_IMAGES.getFit,
  getfit_hero_eyebrow: 'Get Fit Programma',
  getfit_hero_title: 'Fit in 12 weken',
  getfit_hero_subtitle: 'Het complete programma voor jouw transformatie.',
  getfit_banner_title: 'Get Fit Pakket - €1.750,00',
  getfit_banner_subtitle: 'Beperkt aantal plekken beschikbaar!',
  getfit_banner_button: 'Meld Je Aan',
  getfit_included_title: 'Wat zit er inbegrepen?',
  getfit_included_subtitle: 'Geen half werk, maar een complete aanpak op maat. Alles wat je nodig hebt in een krachtig pakket.',
  getfit_item_1_title: '2x per week personal training',
  getfit_item_1_text: '24 sessies in 12 weken onder begeleiding van een ervaren coach',
  getfit_item_2_title: 'Regelmatige weegmomenten',
  getfit_item_2_text: 'Startmeting + iedere 4 weken lichaamsanalyse met rapport',
  getfit_item_3_title: "Voedingsschema's op maat",
  getfit_item_3_text: "Geen crashdieten, maar haalbare schema's die bij jou passen",
  getfit_item_4_title: 'Koelkast-check',
  getfit_item_4_text: 'We kijken samen naar je keuken en maken slimme voedingskeuzes',
  getfit_item_5_title: 'Deep Tissue Massage',
  getfit_item_5_text: 'Eenmaal een krachtige massage voor herstel en prestatieverbetering',
  getfit_item_6_title: 'Mental Coaching',
  getfit_item_6_text: 'Positieve mindset, motivatie en het doorbreken van patronen',
  getfit_item_7_title: '24/7 Support',
  getfit_item_7_text: 'Via app altijd bereikbaar voor vragen en ondersteuning',
  getfit_item_8_title: 'Voortgangsboekje',
  getfit_item_8_text: 'Houd jouw resultaten en mindset overzichtelijk bij',
  getfit_why_title: 'Waarom het Get Fit Pakket?',
  getfit_why_benefits:
    'Een alles-in-een pakket: sport, voeding, herstel en een goede mindset\nGeen standaard oplossing, maar maatwerk en een gerichte persoonlijke aanpak\nExclusieve begeleiding gericht op het aanpassen van jouw patronen\nResultaten die je kunt zien en voelen na 12 weken',
  getfit_cta_title: 'Ben jij klaar voor jouw transformatie?',
  getfit_cta_subtitle: 'Beperkt aantal plekken - meld je vandaag nog aan!',
  getfit_faq_title: 'Veelgestelde Vragen',
  getfit_faq_1_question: 'Hoelang duurt het Get Fit Programma?',
  getfit_faq_1_answer: 'Het programma duurt 12 weken. In deze periode krijg je alle begeleiding die je nodig hebt.',
  getfit_faq_2_question: 'Voor wie is het Get Fit Programma geschikt?',
  getfit_faq_2_answer: 'Voor iedereen die serieus aan de slag wil met fitness en gezondheid. Of je nu wilt afvallen, spiermassa wilt opbouwen of fitter wilt worden.',
  getfit_faq_3_question: 'Moet ik al sportervaring hebben?',
  getfit_faq_3_answer: 'Nee, we passen alles aan op jouw niveau. Het programma is geschikt voor beginners tot gevorderden.',
  getfit_faq_4_question: 'Zijn er nog plekken beschikbaar?',
  getfit_faq_4_answer: 'Het aantal plekken is beperkt om de kwaliteit van begeleiding te garanderen. Neem contact op voor actuele beschikbaarheid.',

  about_hero_image: PAGE_IMAGES.about,
  about_hero_eyebrow: 'Over Ons',
  about_hero_title: 'Jouw guide naar een gezonde lifestyle',
  about_profile_image: PAGE_IMAGES.about,
  about_main_title: 'Wie ben ik',
  about_main_text:
    'JitanSports is ontstaan vanuit ervaring. Ervaring in het na je 40ste er nog steeds goed uit kunnen zien en jezelf goed voelen. Je kunt nog steeds ongelofelijke prestaties behalen en jezelf energieker, vitaler, gelukkiger en zelfverzekerder voelen.\nWij kunnen je helpen om jou deze verandering te laten behalen. Ben jij bereid om de knoop door te hakken, wil je veranderen en een nieuwe lifestyle aannemen? Dan staan wij klaar om jou te helpen.\nJitanSports onderscheidt zich in de wereld van Personal Training en massage door zich te richten op de combinatie Vintage Krachttraining en Deep Tissue Massage.',
  about_card_1_title: 'Mijn Visie',
  about_card_1_text: 'Your health is our goal. JitanSports helpt je om op een verantwoorde manier te trainen, op jouw tempo. Een fitte lifestyle is een goed begin naar jezelf beter voelen.',
  about_card_2_title: 'Mijn Aanpak',
  about_card_2_text: 'Met een luisterend oor en empathie voor jouw doel en situatie gaan wij voor jouw resultaat. Stap voor stap, op jouw eigen tempo - niets moet - we gaan ervoor!',
  about_card_3_title: 'Mijn Certificeringen',
  about_card_3_text: 'Jarenlange ervaring en opleidingen in fitness, Personal Training, voeding en verschillende vormen van massage. Continue bijscholing om de beste begeleiding te bieden.',
  about_card_4_title: 'Mijn Achtergrond',
  about_card_4_text: 'Met jarenlange ervaring in zowel fitness als massage helpen wij je verder. Van krachttraining tot Deep Tissue Massage, van voedingsadvies tot mental coaching.',

  pricing_eyebrow: 'Tarieven',
  pricing_title: 'Investeer in jezelf',
  pricing_subtitle: 'Transparante prijzen, geen verborgen kosten. Eerste proefles altijd gratis.',
  pricing_more_title: 'Overige Diensten',
  pricing_more_1_name: 'Ontspanningsmassage',
  pricing_more_1_desc: 'Full body - 1 uur',
  pricing_more_1_price: '€60,00',
  pricing_more_2_name: 'Stoelmassage',
  pricing_more_2_desc: '20 min (€25) / 30 min (€37,50)',
  pricing_more_2_price: 'vanaf €25,00',
  pricing_more_3_name: 'Voedingsschema',
  pricing_more_3_desc: 'Op maat, voor 1-1,5 maand',
  pricing_more_3_price: '€45,00',
  pricing_more_4_name: 'Lichaamsanalyse',
  pricing_more_4_desc: 'Inclusief digitaal rapport',
  pricing_more_4_price: '€15,00',
  pricing_more_5_name: 'VIP Behandeling',
  pricing_more_5_desc: '1 uur training + 1 uur massage',
  pricing_more_5_price: '€190,00',
  pricing_cta_title: 'Klaar om te starten?',
  pricing_cta_subtitle: 'Plan vandaag nog jouw gratis proefles en ervaar het verschil.',

  blog_eyebrow: 'Blog',
  blog_title: 'Inzichten & Tips',
  blog_subtitle: 'De laatste artikelen over training, voeding en welzijn.',
  faq_eyebrow: 'FAQ',
  faq_title: 'Veelgestelde vragen',
  faq_subtitle: 'Alles wat je wilt weten over personal training, massage, tarieven en online afspraken.',
  faq_not_found_title: 'Staat je vraag er niet bij?',
  faq_not_found_text: 'Stel je vraag direct of plan een gratis kennismaking.',
  faq_not_found_button: 'Neem contact op',
  contact_eyebrow: 'Contact',
  contact_title: 'Neem Contact Op',
  contact_subtitle: 'We horen graag van je. Neem gerust contact op!',
  contact_form_title: 'Stuur een Bericht',
  contact_success_title: 'Bedankt!',
  contact_success_text: 'We nemen zo snel mogelijk contact met je op.',
  contact_details_title: 'Contactgegevens',
  contact_opening_hours_1: 'Ma - Za: 07:00 - 21:00',
  contact_opening_hours_2: 'Zo: Op afspraak',
  contact_whatsapp_title: 'Heb je vragen?',
  contact_whatsapp_text: 'Neem direct contact op via WhatsApp.',
  contact_whatsapp_button: 'WhatsApp Jitan',
  contact_map_url: 'https://www.google.com/maps?q=Den%20Bosch%2C%20Nederland&output=embed',
  booking_title: 'Maak een Afspraak',
  booking_subtitle: 'Gratis proefles of direct boeken - volledig vrijblijvend',
  booking_service_title: 'Kies uw dienst',
  booking_success_title: 'Aanvraag ontvangen!',
  booking_success_text: 'We nemen binnen 24 uur contact op om uw afspraak te bevestigen.',
  booking_new_button: 'Nieuwe afspraak plannen',
  booking_service_1_name: 'Personal Training Outdoor',
  booking_service_1_desc: 'Training in de buitenlucht, op jouw locatie',
  booking_service_1_price: 'Gratis proefles',
  booking_service_1_duration: '60 min',
  booking_service_2_name: 'Personal Training @Home',
  booking_service_2_desc: 'Training aan huis, volledig op maat',
  booking_service_2_price: 'Gratis proefles',
  booking_service_2_duration: '60 min',
  booking_service_3_name: 'Deep Tissue Massage',
  booking_service_3_desc: 'Professionele massage voor herstel en pijn',
  booking_service_3_price: 'Vanaf €65',
  booking_service_3_duration: '60-90 min',
  booking_service_4_name: 'Ontspanningsmassage',
  booking_service_4_desc: 'Diepe ontspanning en stress-relief',
  booking_service_4_price: 'Vanaf €55',
  booking_service_4_duration: '60-90 min',
  booking_service_5_name: 'Get Fit Pakket',
  booking_service_5_desc: 'Compleet transformatieprogramma',
  booking_service_5_price: 'Op aanvraag',
  booking_service_5_duration: '12 weken',
  booking_service_6_name: 'Gratis Proefles',
  booking_service_6_desc: 'Vrijblijvend kennismaken met Jitan',
  booking_service_6_price: 'Gratis',
  booking_service_6_duration: '60 min',

  trainer_db_hero_image: PAGE_IMAGES.trainerDenBosch,
  trainer_db_rating_text: '5.0 · 47+ beoordelingen',
  trainer_db_title: 'Personal Trainer omgeving Den Bosch',
  trainer_db_subtitle:
    'Bereik jouw fitnessdoelen met een ervaren personal trainer in omgeving Den Bosch. Outdoor training, aan huis of bij jou in de buurt. Start met een gratis proefles!',
  trainer_db_primary_button: 'Plan Gratis Proefles',
  trainer_db_section_title: 'Waarom JitanSports als personal trainer in omgeving Den Bosch?',
  trainer_db_section_text:
    'Als personal trainer in omgeving Den Bosch bied ik volledig maatwerk - afgestemd op jouw doelen, niveau en agenda. Of je nu wil afvallen, sterker worden, meer energie wil of minder pijnklachten wilt - ik help je resultaat te boeken.\nMet meer dan 10 jaar ervaring en succesvolle klanten in omgeving Den Bosch weet ik wat werkt. Geen one-size-fits-all, maar jouw persoonlijke programma.',
  trainer_db_features:
    '1-op-1 persoonlijke begeleiding\nTraining op jouw locatie in omgeving Den Bosch\nVoedings- en leefstijladvies inbegrepen\n10+ jaar ervaring als personal trainer\nCombinatie training en massage mogelijk\nGratis kennismakingsles - geen verplichtingen',
  trainer_db_services_title: 'Diensten in omgeving Den Bosch',
  trainer_db_service_1_name: 'Personal Training Outdoor',
  trainer_db_service_1_desc: 'Training in parken en buitenlocaties in omgeving Den Bosch.',
  trainer_db_service_2_name: 'Personal Training @Home',
  trainer_db_service_2_desc: 'Ik kom naar jou toe - geen sportschool nodig.',
  trainer_db_service_3_name: 'Deep Tissue Massage',
  trainer_db_service_3_desc: 'Professionele massage voor herstel en pijnvermindering.',
  trainer_db_service_4_name: 'Get Fit Programma',
  trainer_db_service_4_desc: '12 weken totale transformatie inclusief voeding en coaching.',
  trainer_db_services_button: 'Start met Gratis Proefles',
  trainer_db_areas_title: 'Actief in omgeving Den Bosch',
  trainer_db_areas: 'Den Bosch\nRosmalen\nVught\nOss\nSint-Michielsgestel\nBoxtel\nZaltbommel\nHeusden',
  trainer_db_faq_title: 'Veelgestelde vragen - Personal Trainer omgeving Den Bosch',
  trainer_db_faq_1_question: 'Wat kost een personal trainer in omgeving Den Bosch?',
  trainer_db_faq_1_answer: 'Bij JitanSports start je altijd met een gratis proefles. Daarna gelden vaste tarieven afhankelijk van het gekozen pakket. Bekijk de tarievenpagina voor exacte prijzen.',
  trainer_db_faq_2_question: 'Waar traint JitanSports in omgeving Den Bosch?',
  trainer_db_faq_2_answer: 'We trainen outdoor, aan huis of op een locatie in omgeving Den Bosch die jou uitkomt. Training aan huis is ook mogelijk.',
  trainer_db_faq_3_question: 'Hoe snel zie ik resultaat?',
  trainer_db_faq_3_answer: 'De meeste klanten voelen na 4-6 weken merkbare verbetering in energie, kracht en lichaamsvorm.',
  trainer_db_faq_4_question: 'Is personal training geschikt voor beginners?',
  trainer_db_faq_4_answer: 'Absoluut. De training wordt volledig afgestemd op jouw niveau en doelen. We bouwen rustig en verantwoord op.',
  trainer_db_cta_title: 'Klaar om te starten in omgeving Den Bosch?',
  trainer_db_cta_subtitle: 'Plan vandaag nog je gratis proefles bij JitanSports in omgeving Den Bosch.',

  massage_db_hero_image: PAGE_IMAGES.massageDenBosch,
  massage_db_rating_text: '5.0 · 31+ tevreden klanten',
  massage_db_title: 'Massage omgeving Den Bosch',
  massage_db_subtitle:
    'Professionele massage aan huis of op locatie in omgeving Den Bosch. Verminder pijn, verminder stress en herstel sneller. Direct boeken!',
  massage_db_primary_button: 'Boek een Massage',
  massage_db_section_title: 'Massage aan huis in omgeving Den Bosch',
  massage_db_section_text:
    'JitanSports biedt professionele massagediensten aan huis in omgeving Den Bosch. Geen gedoe met rijden naar een massagepraktijk - ik kom naar jou toe.\nOf je nu chronische rugklachten hebt, last van stress of gewoon wil ontspannen na een drukke werkweek - wij hebben de behandeling die bij jou past.',
  massage_db_features:
    'Massage aan huis in omgeving Den Bosch\nDeep Tissue en ontspanningsmassage\n60 of 90 minuten sessies\nGecertificeerde massagetherapeut\nOok voor chronische pijnklachten\nSnel te boeken via de website',
  massage_db_service_1_name: 'Deep Tissue Massage',
  massage_db_service_1_desc: 'Gericht op diepe spierlagen. Ideaal bij chronische pijn, sportblessures en spanning in nek, schouders en rug.',
  massage_db_service_1_price: 'Vanaf €65',
  massage_db_service_1_duration: '60-90 min',
  massage_db_service_2_name: 'Ontspanningsmassage',
  massage_db_service_2_desc: 'Ontspannende, vloeiende massage. Perfect voor stress-relief, betere slaap en algemeen herstel.',
  massage_db_service_2_price: 'Vanaf €55',
  massage_db_service_2_duration: '60-90 min',
  massage_db_booking_button: 'Direct een massage boeken',
  massage_db_faq_title: 'Veelgestelde vragen - Massage omgeving Den Bosch',
  massage_db_faq_1_question: 'Welke massages zijn beschikbaar in omgeving Den Bosch?',
  massage_db_faq_1_answer: 'JitanSports biedt Deep Tissue Massage en Ontspanningsmassage aan in omgeving Den Bosch. Beide zijn beschikbaar aan huis of op locatie.',
  massage_db_faq_2_question: 'Hoe lang duurt een massage?',
  massage_db_faq_2_answer: 'Massages zijn beschikbaar in 60 of 90 minuten. Voor chronische klachten raden we 90 minuten aan.',
  massage_db_faq_3_question: 'Komt de masseur aan huis?',
  massage_db_faq_3_answer: 'Ja, JitanSports komt naar je toe in omgeving Den Bosch. Geen reiskosten voor locaties in het werkgebied.',
  massage_db_faq_4_question: 'Helpt massage bij rugklachten?',
  massage_db_faq_4_answer: 'Deep Tissue Massage is bijzonder effectief bij chronische rug-, nek- en schouderklachten. Veel klanten voelen al na de eerste sessie verlichting.',
  massage_db_cta_title: 'Boek een massage in omgeving Den Bosch',
  massage_db_cta_subtitle: 'Snel geboekt, professioneel uitgevoerd. Aan huis in omgeving Den Bosch.',

  deep_db_hero_image: PAGE_IMAGES.massageDenBosch,
  deep_db_rating_text: '5.0 · 28+ tevreden klanten',
  deep_db_title: 'Deep Tissue Massage omgeving Den Bosch',
  deep_db_subtitle:
    'Professionele Deep Tissue Massage in omgeving Den Bosch. Effectief bij rugklachten, spierspanning en sportblessures. Aan huis beschikbaar!',
  deep_db_primary_button: 'Boek Deep Tissue Massage',
  deep_db_section_title: 'Wat is Deep Tissue Massage?',
  deep_db_section_text:
    'Deep Tissue Massage is een intensieve massagetechniek gericht op de diepe lagen van spieren en bindweefsel. Door gerichte druk worden chronische spanning, knooppunten en verklevingen losgemaakt die oppervlakkige massages niet bereiken.\nBij JitanSports combineer ik diepgaande kennis van anatomie met jarenlange praktijkervaring. Resultaat: blijvende verlichting van klachten in plaats van tijdelijk comfort.',
  deep_db_benefits_title: 'Voordelen',
  deep_db_benefits:
    'Vermindert chronische rugpijn\nLost spierspanning en knooppunten op\nVerbetert doorbloeding\nVermindert sportblessures\nHelpt bij nekpijn en schouderpijn\nStimuleert herstel na training',
  deep_db_card_title: 'Deep Tissue Massage',
  deep_db_card_text: 'Intensieve behandeling voor chronische klachten en sportblessures.',
  deep_db_price_1: '€65',
  deep_db_price_1_label: '60 minuten',
  deep_db_price_2: '€85',
  deep_db_price_2_label: '90 minuten',
  deep_db_card_button: 'Nu boeken',
  deep_db_combine_title: 'Combineer voor maximaal effect:',
  deep_db_combine_text:
    'Klanten die Deep Tissue Massage combineren met personal training bereiken snellere herstel, minder blessures en betere trainingsresultaten.',
  deep_db_combine_link_text: 'Meer over personal training',
  deep_db_faq_title: 'Veelgestelde vragen - Deep Tissue Massage omgeving Den Bosch',
  deep_db_faq_1_question: 'Wat is Deep Tissue Massage precies?',
  deep_db_faq_1_answer: 'Deep Tissue Massage richt zich op de diepere lagen van spieren en bindweefsel. Met gerichte druk worden gespannen spieren, knooppunten en littekens losgemaakt.',
  deep_db_faq_2_question: 'Is Deep Tissue Massage pijnlijk?',
  deep_db_faq_2_answer: 'Tijdens de massage kan er druk worden gevoeld op gespannen gebieden. Dit stemmen we altijd af, zodat de behandeling effectief en verantwoord blijft.',
  deep_db_faq_3_question: 'Hoe vaak moet ik een Deep Tissue Massage krijgen?',
  deep_db_faq_3_answer: 'Voor chronische klachten starten veel klanten wekelijks en bouwen daarna af naar onderhoud. We bespreken samen wat bij jouw lichaam past.',
  deep_db_faq_4_question: 'Welke klachten behandel je met Deep Tissue Massage?',
  deep_db_faq_4_answer: 'Onder andere rugpijn, nekpijn, schouderspanning, sportblessures, spierkrampen en herstel na training. Bij twijfel kun je vooraf contact opnemen.',
  deep_db_faq_5_question: 'Is Deep Tissue Massage aan huis beschikbaar in omgeving Den Bosch?',
  deep_db_faq_5_answer: 'Ja, JitanSports biedt Deep Tissue Massage aan huis in omgeving Den Bosch. Geen reiskosten voor locaties in het werkgebied.',
  deep_db_cta_title: 'Boek uw Deep Tissue Massage in omgeving Den Bosch',
  deep_db_cta_subtitle: 'Aan huis. Professioneel. Effectief. Snel geboekt.',
});

const field = (key, label, type = 'text', order = 0) => ({ key, label, type, order });

const cardFields = (prefix, label, order) => [
  field(`${prefix}_title`, `${label} titel`, 'text', order),
  field(`${prefix}_text`, `${label} tekst`, 'textarea', order + 1),
];

const homeServiceFields = (number, order) => [
  field(`home_service_${number}_title`, `Dienst ${number} titel`, 'text', order),
  field(`home_service_${number}_desc`, `Dienst ${number} tekst`, 'textarea', order + 1),
  field(`home_service_${number}_image`, `Dienst ${number} afbeelding`, 'image_url', order + 2),
  field(`home_service_${number}_link`, `Dienst ${number} link`, 'text', order + 3),
  field(`home_service_${number}_cta`, `Dienst ${number} knoptekst`, 'text', order + 4),
];

const bookingServiceFields = (number, order) => [
  field(`booking_service_${number}_name`, `Dienst ${number} naam`, 'text', order),
  field(`booking_service_${number}_desc`, `Dienst ${number} omschrijving`, 'textarea', order + 1),
  field(`booking_service_${number}_price`, `Dienst ${number} prijslabel`, 'text', order + 2),
  field(`booking_service_${number}_duration`, `Dienst ${number} duur`, 'text', order + 3),
];

const pricingMoreFields = (number, order) => [
  field(`pricing_more_${number}_name`, `Extra dienst ${number} naam`, 'text', order),
  field(`pricing_more_${number}_desc`, `Extra dienst ${number} omschrijving`, 'text', order + 1),
  field(`pricing_more_${number}_price`, `Extra dienst ${number} prijs`, 'text', order + 2),
];

const faqFields = (prefix, label, order) => [
  field(`${prefix}_question`, `${label} vraag`, 'text', order),
  field(`${prefix}_answer`, `${label} antwoord`, 'textarea', order + 1),
];

const seoFields = (prefix, label, order) => [
  field(`seo_${prefix}_title`, `${label} SEO titel`, 'text', order),
  field(`seo_${prefix}_description`, `${label} meta description`, 'textarea', order + 1),
];

export const CONTENT_FIELDS = [
  {
    group: 'Homepage hero',
    fields: [
      field('hero_eyebrow', 'Hero label', 'text', 10),
      field('hero_title', 'Hero titel', 'text', 20),
      field('hero_highlight', 'Hero accentregel', 'text', 30),
      field('hero_subtitle', 'Hero tekst', 'textarea', 40),
      field('hero_image', 'Hero afbeelding', 'image_url', 50),
      field('primary_cta_text', 'Primaire knoptekst', 'text', 60),
      field('secondary_cta_text', 'Secundaire knoptekst', 'text', 70),
      field('home_review_proof', 'Review/social proof tekst', 'text', 80),
    ],
  },
  {
    group: 'Homepage doelen en statistieken',
    fields: [
      field('goal_eyebrow', 'Doelen label', 'text', 100),
      field('goal_title', 'Doelen titel', 'text', 110),
      ...cardFields('goal_1', 'Doel 1', 120),
      field('goal_1_cta', 'Doel 1 knoptekst', 'text', 122),
      field('goal_1_link', 'Doel 1 link', 'text', 123),
      ...cardFields('goal_2', 'Doel 2', 130),
      field('goal_2_cta', 'Doel 2 knoptekst', 'text', 132),
      field('goal_2_link', 'Doel 2 link', 'text', 133),
      ...cardFields('goal_3', 'Doel 3', 140),
      field('goal_3_cta', 'Doel 3 knoptekst', 'text', 142),
      field('goal_3_link', 'Doel 3 link', 'text', 143),
      ...cardFields('goal_4', 'Doel 4', 150),
      field('goal_4_cta', 'Doel 4 knoptekst', 'text', 152),
      field('goal_4_link', 'Doel 4 link', 'text', 153),
      field('stat_1_value', 'Statistiek 1 waarde', 'text', 170),
      field('stat_1_label', 'Statistiek 1 label', 'text', 171),
      field('stat_2_value', 'Statistiek 2 waarde', 'text', 172),
      field('stat_2_label', 'Statistiek 2 label', 'text', 173),
      field('stat_3_value', 'Statistiek 3 waarde', 'text', 174),
      field('stat_3_label', 'Statistiek 3 label', 'text', 175),
      field('stat_4_value', 'Statistiek 4 waarde', 'text', 176),
      field('stat_4_label', 'Statistiek 4 label', 'text', 177),
    ],
  },
  {
    group: 'Homepage diensten en over',
    fields: [
      field('home_services_eyebrow', 'Diensten label', 'text', 200),
      field('home_services_title', 'Diensten titel', 'text', 210),
      ...homeServiceFields(1, 220),
      ...homeServiceFields(2, 230),
      ...homeServiceFields(3, 240),
      field('home_mid_cta_title', 'Tussen-CTA titel', 'text', 260),
      field('home_mid_cta_text', 'Tussen-CTA tekst', 'textarea', 261),
      field('home_mid_cta_button', 'Tussen-CTA knoptekst', 'text', 262),
      field('home_about_eyebrow', 'Over label', 'text', 270),
      field('home_about_title', 'Over titel', 'text', 271),
      field('home_about_text', 'Over tekst', 'textarea', 272),
      field('home_about_image', 'Over afbeelding', 'image_url', 273),
      field('home_about_usps', 'Over USP lijst (1 per regel)', 'textarea', 274),
      field('home_about_button', 'Over knoptekst', 'text', 275),
      field('home_faq_title', 'FAQ titel op homepage', 'text', 280),
      ...faqFields('home_faq_1', 'Homepage FAQ 1', 281),
      ...faqFields('home_faq_2', 'Homepage FAQ 2', 283),
      ...faqFields('home_faq_3', 'Homepage FAQ 3', 285),
      ...faqFields('home_faq_4', 'Homepage FAQ 4', 287),
      field('gallery_eyebrow', 'Galerij label', 'text', 290),
      field('gallery_title', 'Galerij titel', 'text', 291),
    ],
  },
  {
    group: 'Personal Training pagina',
    fields: [
      field('pt_hero_image', 'Hero afbeelding', 'image_url', 300),
      field('pt_hero_eyebrow', 'Hero label', 'text', 301),
      field('pt_hero_title', 'Hero titel', 'text', 302),
      field('pt_hero_subtitle', 'Hero tekst', 'textarea', 303),
      field('pt_banner_text', 'Banner tekst', 'text', 304),
      field('pt_banner_button', 'Banner knoptekst', 'text', 305),
      field('pt_main_title', 'Hoofdsectie titel', 'text', 310),
      field('pt_main_text', 'Hoofdsectie tekst (alinea per regel)', 'textarea', 311),
      field('pt_benefits', 'Voordelen (1 per regel)', 'textarea', 312),
      ...cardFields('pt_feature_1', 'Feature 1', 320),
      ...cardFields('pt_feature_2', 'Feature 2', 330),
      ...cardFields('pt_feature_3', 'Feature 3', 340),
      ...cardFields('pt_feature_4', 'Feature 4', 350),
      field('pt_nutrition_title', 'Voedingssectie titel', 'text', 360),
      field('pt_nutrition_text', 'Voedingssectie tekst (alinea per regel)', 'textarea', 361),
      field('pt_nutrition_button', 'Voedingssectie knoptekst', 'text', 362),
      field('pt_faq_title', 'FAQ titel', 'text', 370),
      ...faqFields('pt_faq_1', 'FAQ 1', 371),
      ...faqFields('pt_faq_2', 'FAQ 2', 373),
      ...faqFields('pt_faq_3', 'FAQ 3', 375),
      ...faqFields('pt_faq_4', 'FAQ 4', 377),
    ],
  },
  {
    group: 'Massage pagina',
    fields: [
      field('massage_hero_image', 'Hero afbeelding', 'image_url', 400),
      field('massage_hero_eyebrow', 'Hero label', 'text', 401),
      field('massage_hero_title', 'Hero titel', 'text', 402),
      field('massage_hero_subtitle', 'Hero tekst', 'textarea', 403),
      field('massage_banner_text', 'Banner tekst', 'text', 404),
      field('massage_banner_button', 'Banner knoptekst', 'text', 405),
      field('massage_popular_label', 'Badge tekst', 'text', 406),
      field('massage_main_title', 'Hoofdsectie titel', 'text', 410),
      field('massage_main_text', 'Hoofdsectie tekst (alinea per regel)', 'textarea', 411),
      field('massage_benefits', 'Voordelen (1 per regel)', 'textarea', 412),
      field('massage_price_text', 'Prijs tekst', 'text', 413),
      field('massage_price_subtext', 'Prijs subtekst', 'text', 414),
      ...cardFields('massage_card_1', 'Kaart 1', 420),
      field('massage_card_1_price', 'Kaart 1 prijs', 'text', 422),
      ...cardFields('massage_card_2', 'Kaart 2', 430),
      field('massage_card_2_price', 'Kaart 2 prijs', 'text', 432),
      field('massage_process_title', 'Proces titel', 'text', 440),
      field('massage_step_1_title', 'Stap 1 titel', 'text', 441),
      field('massage_step_1_text', 'Stap 1 tekst', 'text', 442),
      field('massage_step_2_title', 'Stap 2 titel', 'text', 443),
      field('massage_step_2_text', 'Stap 2 tekst', 'text', 444),
      field('massage_step_3_title', 'Stap 3 titel', 'text', 445),
      field('massage_step_3_text', 'Stap 3 tekst', 'text', 446),
      field('massage_cta_title', 'CTA titel', 'text', 450),
      field('massage_cta_subtitle', 'CTA tekst', 'textarea', 451),
    ],
  },
  {
    group: 'Get Fit pagina',
    fields: [
      field('getfit_hero_image', 'Hero afbeelding', 'image_url', 500),
      field('getfit_hero_eyebrow', 'Hero label', 'text', 501),
      field('getfit_hero_title', 'Hero titel', 'text', 502),
      field('getfit_hero_subtitle', 'Hero tekst', 'textarea', 503),
      field('getfit_banner_title', 'Prijsbanner titel', 'text', 504),
      field('getfit_banner_subtitle', 'Prijsbanner tekst', 'text', 505),
      field('getfit_banner_button', 'Prijsbanner knoptekst', 'text', 506),
      field('getfit_included_title', 'Inbegrepen titel', 'text', 510),
      field('getfit_included_subtitle', 'Inbegrepen tekst', 'textarea', 511),
      ...cardFields('getfit_item_1', 'Onderdeel 1', 520),
      ...cardFields('getfit_item_2', 'Onderdeel 2', 530),
      ...cardFields('getfit_item_3', 'Onderdeel 3', 540),
      ...cardFields('getfit_item_4', 'Onderdeel 4', 550),
      ...cardFields('getfit_item_5', 'Onderdeel 5', 560),
      ...cardFields('getfit_item_6', 'Onderdeel 6', 570),
      ...cardFields('getfit_item_7', 'Onderdeel 7', 580),
      ...cardFields('getfit_item_8', 'Onderdeel 8', 590),
      field('getfit_why_title', 'Waarom titel', 'text', 600),
      field('getfit_why_benefits', 'Waarom punten (1 per regel)', 'textarea', 601),
      field('getfit_cta_title', 'CTA titel', 'text', 610),
      field('getfit_cta_subtitle', 'CTA tekst', 'textarea', 611),
      field('getfit_faq_title', 'FAQ titel', 'text', 620),
      ...faqFields('getfit_faq_1', 'FAQ 1', 621),
      ...faqFields('getfit_faq_2', 'FAQ 2', 623),
      ...faqFields('getfit_faq_3', 'FAQ 3', 625),
      ...faqFields('getfit_faq_4', 'FAQ 4', 627),
    ],
  },
  {
    group: 'Over ons pagina',
    fields: [
      field('about_hero_image', 'Hero afbeelding', 'image_url', 700),
      field('about_hero_eyebrow', 'Hero label', 'text', 701),
      field('about_hero_title', 'Hero titel', 'text', 702),
      field('about_profile_image', 'Profiel afbeelding', 'image_url', 703),
      field('about_main_title', 'Hoofdsectie titel', 'text', 704),
      field('about_main_text', 'Hoofdsectie tekst (alinea per regel)', 'textarea', 705),
      ...cardFields('about_card_1', 'Blok 1', 710),
      ...cardFields('about_card_2', 'Blok 2', 720),
      ...cardFields('about_card_3', 'Blok 3', 730),
      ...cardFields('about_card_4', 'Blok 4', 740),
    ],
  },
  {
    group: 'Tarieven pagina',
    fields: [
      field('pricing_eyebrow', 'Hero label', 'text', 800),
      field('pricing_title', 'Hero titel', 'text', 801),
      field('pricing_subtitle', 'Hero tekst', 'textarea', 802),
      field('pricing_more_title', 'Extra diensten titel', 'text', 810),
      ...pricingMoreFields(1, 820),
      ...pricingMoreFields(2, 830),
      ...pricingMoreFields(3, 840),
      ...pricingMoreFields(4, 850),
      ...pricingMoreFields(5, 860),
      field('pricing_cta_title', 'CTA titel', 'text', 870),
      field('pricing_cta_subtitle', 'CTA tekst', 'textarea', 871),
    ],
  },
  {
    group: 'Blog, FAQ, contact en booking',
    fields: [
      field('blog_eyebrow', 'Blog label', 'text', 900),
      field('blog_title', 'Blog titel', 'text', 901),
      field('blog_subtitle', 'Blog tekst', 'textarea', 902),
      field('faq_eyebrow', 'FAQ label', 'text', 910),
      field('faq_title', 'FAQ titel', 'text', 911),
      field('faq_subtitle', 'FAQ tekst', 'textarea', 912),
      field('faq_not_found_title', 'FAQ contactblok titel', 'text', 913),
      field('faq_not_found_text', 'FAQ contactblok tekst', 'textarea', 914),
      field('faq_not_found_button', 'FAQ contactblok knoptekst', 'text', 915),
      field('contact_eyebrow', 'Contact label', 'text', 920),
      field('contact_title', 'Contact titel', 'text', 921),
      field('contact_subtitle', 'Contact tekst', 'textarea', 922),
      field('contact_form_title', 'Contact formulier titel', 'text', 923),
      field('contact_success_title', 'Contact succes titel', 'text', 924),
      field('contact_success_text', 'Contact succes tekst', 'textarea', 925),
      field('contact_details_title', 'Contactgegevens titel', 'text', 926),
      field('contact_opening_hours_1', 'Openingstijden regel 1', 'text', 927),
      field('contact_opening_hours_2', 'Openingstijden regel 2', 'text', 928),
      field('contact_whatsapp_title', 'WhatsApp blok titel', 'text', 929),
      field('contact_whatsapp_text', 'WhatsApp blok tekst', 'textarea', 930),
      field('contact_whatsapp_button', 'WhatsApp knoptekst', 'text', 931),
      field('contact_map_url', 'Google Maps embed URL', 'url', 932),
      field('booking_title', 'Booking titel', 'text', 940),
      field('booking_subtitle', 'Booking tekst', 'textarea', 941),
      field('booking_service_title', 'Booking dienst-stap titel', 'text', 942),
      field('booking_success_title', 'Booking succes titel', 'text', 943),
      field('booking_success_text', 'Booking succes tekst', 'textarea', 944),
      field('booking_new_button', 'Booking nieuwe afspraak knoptekst', 'text', 945),
      ...bookingServiceFields(1, 950),
      ...bookingServiceFields(2, 960),
      ...bookingServiceFields(3, 970),
      ...bookingServiceFields(4, 980),
      ...bookingServiceFields(5, 990),
      ...bookingServiceFields(6, 1000),
    ],
  },
  {
    group: 'SEO pagina Personal Trainer Den Bosch',
    fields: [
      field('trainer_db_hero_image', 'Hero afbeelding', 'image_url', 1100),
      field('trainer_db_rating_text', 'Rating tekst', 'text', 1101),
      field('trainer_db_title', 'Hero titel', 'text', 1102),
      field('trainer_db_subtitle', 'Hero tekst', 'textarea', 1103),
      field('trainer_db_primary_button', 'Primaire knoptekst', 'text', 1104),
      field('trainer_db_section_title', 'Hoofdsectie titel', 'text', 1110),
      field('trainer_db_section_text', 'Hoofdsectie tekst (alinea per regel)', 'textarea', 1111),
      field('trainer_db_features', 'Voordelen (1 per regel)', 'textarea', 1112),
      field('trainer_db_services_title', 'Diensten blok titel', 'text', 1113),
      field('trainer_db_service_1_name', 'Dienst 1 naam', 'text', 1114),
      field('trainer_db_service_1_desc', 'Dienst 1 tekst', 'textarea', 1115),
      field('trainer_db_service_2_name', 'Dienst 2 naam', 'text', 1116),
      field('trainer_db_service_2_desc', 'Dienst 2 tekst', 'textarea', 1117),
      field('trainer_db_service_3_name', 'Dienst 3 naam', 'text', 1118),
      field('trainer_db_service_3_desc', 'Dienst 3 tekst', 'textarea', 1119),
      field('trainer_db_service_4_name', 'Dienst 4 naam', 'text', 1120),
      field('trainer_db_service_4_desc', 'Dienst 4 tekst', 'textarea', 1121),
      field('trainer_db_services_button', 'Diensten blok knoptekst', 'text', 1122),
      field('trainer_db_areas_title', 'Werkgebied titel', 'text', 1130),
      field('trainer_db_areas', 'Werkgebieden (1 per regel)', 'textarea', 1131),
      field('trainer_db_faq_title', 'FAQ titel', 'text', 1140),
      ...faqFields('trainer_db_faq_1', 'FAQ 1', 1141),
      ...faqFields('trainer_db_faq_2', 'FAQ 2', 1143),
      ...faqFields('trainer_db_faq_3', 'FAQ 3', 1145),
      ...faqFields('trainer_db_faq_4', 'FAQ 4', 1147),
      field('trainer_db_cta_title', 'CTA titel', 'text', 1150),
      field('trainer_db_cta_subtitle', 'CTA tekst', 'textarea', 1151),
    ],
  },
  {
    group: 'SEO pagina Massage Den Bosch',
    fields: [
      field('massage_db_hero_image', 'Hero afbeelding', 'image_url', 1200),
      field('massage_db_rating_text', 'Rating tekst', 'text', 1201),
      field('massage_db_title', 'Hero titel', 'text', 1202),
      field('massage_db_subtitle', 'Hero tekst', 'textarea', 1203),
      field('massage_db_primary_button', 'Primaire knoptekst', 'text', 1204),
      field('massage_db_section_title', 'Hoofdsectie titel', 'text', 1210),
      field('massage_db_section_text', 'Hoofdsectie tekst (alinea per regel)', 'textarea', 1211),
      field('massage_db_features', 'Voordelen (1 per regel)', 'textarea', 1212),
      field('massage_db_service_1_name', 'Dienst 1 naam', 'text', 1220),
      field('massage_db_service_1_desc', 'Dienst 1 tekst', 'textarea', 1221),
      field('massage_db_service_1_price', 'Dienst 1 prijs', 'text', 1222),
      field('massage_db_service_1_duration', 'Dienst 1 duur', 'text', 1223),
      field('massage_db_service_2_name', 'Dienst 2 naam', 'text', 1230),
      field('massage_db_service_2_desc', 'Dienst 2 tekst', 'textarea', 1231),
      field('massage_db_service_2_price', 'Dienst 2 prijs', 'text', 1232),
      field('massage_db_service_2_duration', 'Dienst 2 duur', 'text', 1233),
      field('massage_db_booking_button', 'Boekingsknop tekst', 'text', 1234),
      field('massage_db_faq_title', 'FAQ titel', 'text', 1240),
      ...faqFields('massage_db_faq_1', 'FAQ 1', 1241),
      ...faqFields('massage_db_faq_2', 'FAQ 2', 1243),
      ...faqFields('massage_db_faq_3', 'FAQ 3', 1245),
      ...faqFields('massage_db_faq_4', 'FAQ 4', 1247),
      field('massage_db_cta_title', 'CTA titel', 'text', 1250),
      field('massage_db_cta_subtitle', 'CTA tekst', 'textarea', 1251),
    ],
  },
  {
    group: 'SEO pagina Deep Tissue Den Bosch',
    fields: [
      field('deep_db_hero_image', 'Hero afbeelding', 'image_url', 1300),
      field('deep_db_rating_text', 'Rating tekst', 'text', 1301),
      field('deep_db_title', 'Hero titel', 'text', 1302),
      field('deep_db_subtitle', 'Hero tekst', 'textarea', 1303),
      field('deep_db_primary_button', 'Primaire knoptekst', 'text', 1304),
      field('deep_db_section_title', 'Hoofdsectie titel', 'text', 1310),
      field('deep_db_section_text', 'Hoofdsectie tekst (alinea per regel)', 'textarea', 1311),
      field('deep_db_benefits_title', 'Voordelen titel', 'text', 1312),
      field('deep_db_benefits', 'Voordelen (1 per regel)', 'textarea', 1313),
      field('deep_db_card_title', 'Prijskaart titel', 'text', 1320),
      field('deep_db_card_text', 'Prijskaart tekst', 'textarea', 1321),
      field('deep_db_price_1', 'Prijs 1', 'text', 1322),
      field('deep_db_price_1_label', 'Prijs 1 label', 'text', 1323),
      field('deep_db_price_2', 'Prijs 2', 'text', 1324),
      field('deep_db_price_2_label', 'Prijs 2 label', 'text', 1325),
      field('deep_db_card_button', 'Prijskaart knoptekst', 'text', 1326),
      field('deep_db_combine_title', 'Combinatieblok titel', 'text', 1330),
      field('deep_db_combine_text', 'Combinatieblok tekst', 'textarea', 1331),
      field('deep_db_combine_link_text', 'Combinatieblok linktekst', 'text', 1332),
      field('deep_db_faq_title', 'FAQ titel', 'text', 1340),
      ...faqFields('deep_db_faq_1', 'FAQ 1', 1341),
      ...faqFields('deep_db_faq_2', 'FAQ 2', 1343),
      ...faqFields('deep_db_faq_3', 'FAQ 3', 1345),
      ...faqFields('deep_db_faq_4', 'FAQ 4', 1347),
      ...faqFields('deep_db_faq_5', 'FAQ 5', 1349),
      field('deep_db_cta_title', 'CTA titel', 'text', 1360),
      field('deep_db_cta_subtitle', 'CTA tekst', 'textarea', 1361),
    ],
  },
  {
    group: 'SEO per pagina',
    fields: [
      ...seoFields('home', 'Homepage', 1370),
      ...seoFields('personal_training', 'Personal Training', 1372),
      ...seoFields('massage', 'Massage', 1374),
      ...seoFields('get_fit', 'Get Fit', 1376),
      ...seoFields('about', 'Over ons', 1378),
      ...seoFields('pricing', 'Tarieven', 1380),
      ...seoFields('blog', 'Blog', 1382),
      ...seoFields('faq', 'FAQ', 1384),
      ...seoFields('contact', 'Contact', 1386),
      ...seoFields('booking', 'Booking', 1388),
      ...seoFields('trainer_den_bosch', 'SEO personal trainer Den Bosch', 1390),
      ...seoFields('massage_den_bosch', 'SEO massage Den Bosch', 1392),
      ...seoFields('deep_tissue_den_bosch', 'SEO deep tissue Den Bosch', 1394),
    ],
  },
  {
    group: 'Algemene CTA, contact en SEO',
    fields: [
      field('cta_title', 'Algemene CTA titel', 'text', 1400),
      field('cta_subtitle', 'Algemene CTA tekst', 'textarea', 1401),
      field('phone_display', 'Telefoon zichtbaar', 'text', 1410),
      field('phone_href', 'Telefoon link', 'tel', 1411),
      field('whatsapp_number', 'WhatsApp nummer', 'tel', 1412),
      field('whatsapp_message', 'WhatsApp standaardbericht', 'textarea', 1413),
      field('email', 'E-mailadres', 'email', 1414),
      field('region', 'Werkgebied', 'text', 1415),
      field('address_label', 'Locatie label', 'text', 1416),
      field('instagram_url', 'Instagram URL', 'url', 1417),
      field('facebook_url', 'Facebook URL', 'url', 1418),
      field('linkedin_url', 'LinkedIn URL', 'url', 1419),
      field('seo_title', 'Standaard SEO titel', 'text', 1420),
      field('seo_description', 'Standaard meta description', 'textarea', 1421),
      field('seo_image', 'Social share afbeelding', 'image_url', 1422),
    ],
  },
];

export function flattenContentFields() {
  return CONTENT_FIELDS.flatMap((section) =>
    section.fields.map((entry) => ({
      ...entry,
      group: section.group,
      value: DEFAULT_SITE_CONTENT[entry.key] || '',
    }))
  );
}

export function mergeSiteContent(rows = []) {
  const merged = { ...DEFAULT_SITE_CONTENT };
  rows.forEach((row) => {
    if (row?.key && typeof row.value === 'string') {
      merged[row.key] = row.value;
    }
  });
  return merged;
}

export function contentLines(content, key) {
  return String(content?.[key] ?? DEFAULT_SITE_CONTENT[key] ?? '')
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean);
}

export function createWhatsAppUrl(content = DEFAULT_SITE_CONTENT, message) {
  const number = String(content.whatsapp_number || DEFAULT_SITE_CONTENT.whatsapp_number).replace(/\D/g, '');
  const text = message || content.whatsapp_message || DEFAULT_SITE_CONTENT.whatsapp_message;
  return `https://wa.me/${number}?text=${encodeURIComponent(text)}`;
}
